spring:
  application.name: cart-service
  jpa:
    database-platform: H2
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server.port: 9003
