spring:
  application.name: store-service
  sleuth.sampler.percentage: 1

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server.port: 8080

logging.level:
  com.netflix.eureka: error
  com.netflix.discovery: error
